# Generated by Django 4.1.2 on 2023-10-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writeblog', models.TextField(max_length=200)),
                ('authornm', models.CharField(max_length=30)),
            ],
        ),
    ]
